# Importing Modules and Dataset 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
plt.style.use('dark_background') 
import warnings 
warnings.filterwarnings(action = 'ignore') 
import seaborn as sns
import difflib #comparison
from sklearn.feature_extraction.text import TfidfVectorizer # to convert text to numerical data
from sklearn.metrics.pairwise import cosine_similarity # similarity scores

In [2]:
df = pd.read_csv('final_playlist.csv')
df.head()

Track URI             Track Name  \
0  spotify:track:6SRWhUJcD2YKahCwHavz3X               Darkside   
1  spotify:track:3u1S1OmAUhx5DRlLrXqyp3                   Rise   
2  spotify:track:18YRKiIZO4qDEc5Ik0Cry6  FRIENDS - R3hab Remix   
3  spotify:track:09IStsImFySgyp0pIQdqAc             The Middle   
4  spotify:track:0E9ZjEAyAwOXZ7wJC0PD33             In My Mind   

                                       Artist URI(s)  \
0  spotify:artist:7vk5e3vY1uw9plTHJAMwjN, spotify...   
1  spotify:artist:1HBjj22wzbscIZ9sEb5dyf, spotify...   
2  spotify:artist:64KEffDW9EtZ1y2vBYgq8T, spotify...   
3  spotify:artist:2qxJFvFYMEDqd7ui6kSAcq, spotify...   
4  spotify:artist:3v6Ji4uoWtKRkhuDUaxi9n, spotify...   

                      Artist Name(s)                             Album URI  \
0  Alan Walker, Au/Ra, Tomine Harket  spotify:album:3nzuGtN3nXARvvecier4K0   
1            Jonas Blue, Jack & Jack  spotify:album:3KjCdhPbjbLptyJzviKu4P   
2      Marshmello, Anne-Marie, R3HAB  spotify:album:2KBVjOOFq54CcaHTxItDhl   
3           Zedd, Maren Morris, Grey  spotify:album:7nEiwcUSwycvC77kZ9ub7c   
4            Dynoro, Gigi D'Agostino  spotify:album:1c79SozES9Eb3Lzf9KVaIa   

              Album Name                                Album Artist URI(s)  \
0        Different World              spotify:artist:7vk5e3vY1uw9plTHJAMwjN   
1                   Rise  spotify:artist:1HBjj22wzbscIZ9sEb5dyf, spotify...   
2  FRIENDS (R3hab Remix)  spotify:artist:64KEffDW9EtZ1y2vBYgq8T, spotify...   
3             The Middle  spotify:artist:2qxJFvFYMEDqd7ui6kSAcq, spotify...   
4             In My Mind  spotify:artist:3v6Ji4uoWtKRkhuDUaxi9n, spotify...   

            Album Artist Name(s) Album Release Date  \
0                    Alan Walker         14-12-2018   
1        Jonas Blue, Jack & Jack         25-05-2018   
2  Marshmello, Anne-Marie, R3HAB         23-03-2018   
3       Zedd, Maren Morris, Grey         23-01-2018   
4        Dynoro, Gigi D'Agostino         08-06-2018   

                                     Album Image URL  Disc Number  \
0  https://i.scdn.co/image/ab67616d0000b273a108e0...            1   
1  https://i.scdn.co/image/ab67616d0000b273ffe7d2...            1   
2  https://i.scdn.co/image/ab67616d0000b2737160be...            1   
3  https://i.scdn.co/image/ab67616d0000b273fbe22d...            1   
4  https://i.scdn.co/image/ab67616d0000b27328a8a0...            1   

   Track Number  Track Duration (ms)  \
0            11               211680   
1             1               194407   
2             1               157142   
3             1               184732   
4             1               184560   

                                   Track Preview URL  Explicit  Popularity  \
0  https://p.scdn.co/mp3-preview/b5e08f76dc4dab3e...     False          72   
1  https://p.scdn.co/mp3-preview/5ec55e481ac31fad...     False          67   
2  https://p.scdn.co/mp3-preview/e2898bbfe10408ca...      True          57   
3  https://p.scdn.co/mp3-preview/0888eaf5d30f8a58...     False          79   
4  https://p.scdn.co/mp3-preview/14d056cbf98e9933...     False          77   

                                 Added By              Added At  Unnamed: 18  \
0  spotify:user:6lvql4lfbafry09uhcovjqpv9  2022-05-29T12:44:42Z          NaN   
1  spotify:user:6lvql4lfbafry09uhcovjqpv9  2022-05-29T12:44:42Z          NaN   
2  spotify:user:6lvql4lfbafry09uhcovjqpv9  2022-05-29T12:44:42Z          NaN   
3  spotify:user:6lvql4lfbafry09uhcovjqpv9  2022-05-29T12:44:42Z          NaN   
4  spotify:user:6lvql4lfbafry09uhcovjqpv9  2022-05-29T12:44:42Z          NaN   

   Index  
0      0  
1      1  
2      2  
3      3  
4      4

In [3]:
df.shape

(1238, 20)

# Data preprocessing

In [4]:
df.info() #check if there are any missing values in important featured

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238 entries, 0 to 1237
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Track URI             1238 non-null   object 
 1   Track Name            1238 non-null   object 
 2   Artist URI(s)         1238 non-null   object 
 3   Artist Name(s)        1238 non-null   object 
 4   Album URI             1238 non-null   object 
 5   Album Name            1238 non-null   object 
 6   Album Artist URI(s)   1238 non-null   object 
 7   Album Artist Name(s)  1238 non-null   object 
 8   Album Release Date    1238 non-null   object 
 9   Album Image URL       1238 non-null   object 
 10  Disc Number           1238 non-null   int64  
 11  Track Number          1238 non-null   int64  
 12  Track Duration (ms)   1238 non-null   int64  
 13  Track Preview URL     1040 non-null   object 
 14  Explicit              1238 non-null   bool   
 15  Popularity           

In [5]:
df  = df.drop(['Track URI','Track Preview URL','Added By','Added At'],axis=1) 
# dropping them isnt gonna make difference as we consider important features only

In [6]:
df = df.rename(columns = {'Track Name' : 'Track'}) #renaming it due to syntax error

In [7]:
df = df.rename(columns = {'Artist Name(s)' : 'Artist'})

In [8]:
df = df.rename(columns = {'Album Name' : 'Album'})

In [9]:
df = df.rename(columns = {'Album Artist Name(s)' : 'Album_Artist'})

In [10]:
df.head(5)

Track                                      Artist URI(s)  \
0               Darkside  spotify:artist:7vk5e3vY1uw9plTHJAMwjN, spotify...   
1                   Rise  spotify:artist:1HBjj22wzbscIZ9sEb5dyf, spotify...   
2  FRIENDS - R3hab Remix  spotify:artist:64KEffDW9EtZ1y2vBYgq8T, spotify...   
3             The Middle  spotify:artist:2qxJFvFYMEDqd7ui6kSAcq, spotify...   
4             In My Mind  spotify:artist:3v6Ji4uoWtKRkhuDUaxi9n, spotify...   

                              Artist                             Album URI  \
0  Alan Walker, Au/Ra, Tomine Harket  spotify:album:3nzuGtN3nXARvvecier4K0   
1            Jonas Blue, Jack & Jack  spotify:album:3KjCdhPbjbLptyJzviKu4P   
2      Marshmello, Anne-Marie, R3HAB  spotify:album:2KBVjOOFq54CcaHTxItDhl   
3           Zedd, Maren Morris, Grey  spotify:album:7nEiwcUSwycvC77kZ9ub7c   
4            Dynoro, Gigi D'Agostino  spotify:album:1c79SozES9Eb3Lzf9KVaIa   

                   Album                                Album Artist URI(s)  \
0        Different World              spotify:artist:7vk5e3vY1uw9plTHJAMwjN   
1                   Rise  spotify:artist:1HBjj22wzbscIZ9sEb5dyf, spotify...   
2  FRIENDS (R3hab Remix)  spotify:artist:64KEffDW9EtZ1y2vBYgq8T, spotify...   
3             The Middle  spotify:artist:2qxJFvFYMEDqd7ui6kSAcq, spotify...   
4             In My Mind  spotify:artist:3v6Ji4uoWtKRkhuDUaxi9n, spotify...   

                    Album_Artist Album Release Date  \
0                    Alan Walker         14-12-2018   
1        Jonas Blue, Jack & Jack         25-05-2018   
2  Marshmello, Anne-Marie, R3HAB         23-03-2018   
3       Zedd, Maren Morris, Grey         23-01-2018   
4        Dynoro, Gigi D'Agostino         08-06-2018   

                                     Album Image URL  Disc Number  \
0  https://i.scdn.co/image/ab67616d0000b273a108e0...            1   
1  https://i.scdn.co/image/ab67616d0000b273ffe7d2...            1   
2  https://i.scdn.co/image/ab67616d0000b2737160be...            1   
3  https://i.scdn.co/image/ab67616d0000b273fbe22d...            1   
4  https://i.scdn.co/image/ab67616d0000b27328a8a0...            1   

   Track Number  Track Duration (ms)  Explicit  Popularity  Unnamed: 18  Index  
0            11               211680     False          72          NaN      0  
1             1               194407     False          67          NaN      1  
2             1               157142      True          57          NaN      2  
3             1               184732     False          79          NaN      3  
4             1               184560     False          77          NaN      4

In [11]:
# selecting the relevant/important features for recommendation (feature selection)

important_features = ['Track','Album','Artist','Album_Artist']
print(important_features)
# more features can be added and similarly we can exclude features if we wish to

['Track', 'Album', 'Artist', 'Album_Artist']


In [12]:
# combining all the selected features

combined_features = df['Track']+' '+df['Album']+' '+df['Artist']+' '+df['Album_Artist']
combined_features.head(10)

0    Darkside Different World Alan Walker, Au/Ra, T...
1    Rise Rise Jonas Blue, Jack & Jack Jonas Blue, ...
2    FRIENDS - R3hab Remix FRIENDS (R3hab Remix) Ma...
3    The Middle The Middle Zedd, Maren Morris, Grey...
4    In My Mind In My Mind Dynoro, Gigi D'Agostino ...
5                          REMEDY REMEDY Alesso Alesso
6    Sick Boy Sick Boy The Chainsmokers The Chainsm...
7    We Don't Care We Don't Care Sigala, The Vamps ...
8    Ignite Ignite Alan Walker, Julie Bergan, K-391...
9    WTF (feat. Amber Van Day) WTF (feat. Amber Van...
dtype: object

In [13]:
# converting the text data to feature vectors(numerical values)

vectors = TfidfVectorizer()

In [14]:
feature_vectors = vectors.fit_transform(combined_features)

In [15]:
print(feature_vectors)

  (0, 1186)	0.33611348431312305
  (0, 2833)	0.33611348431312305
  (0, 2187)	0.33611348431312305
  (0, 241)	0.33611348431312305
  (0, 3005)	0.3989149582584469
  (0, 97)	0.40114934177821804
  (0, 3079)	0.22368644877494967
  (0, 758)	0.255047177238792
  (0, 695)	0.33611348431312305
  (1, 1350)	0.7591829330656457
  (1, 388)	0.34893416954623657
  (1, 1401)	0.36247802596778894
  (1, 2307)	0.41291149191493387
  (2, 1734)	0.3702381337986851
  (2, 164)	0.3702381337986851
  (2, 1741)	0.3245505577551743
  (2, 2258)	0.22649287027904857
  (2, 2186)	0.6573728683307246
  (2, 1045)	0.3702381337986851
  (3, 1142)	0.4042448948010109
  (3, 1857)	0.4744008716310721
  (3, 1732)	0.4744008716310721
  (3, 3122)	0.39440102937746796
  (3, 1801)	0.4485083879739663
  (3, 2774)	0.1725159266898733
  :	:
  (1233, 885)	0.6745787821883908
  (1233, 634)	0.3372893910941954
  (1233, 1990)	0.22213445816917665
  (1234, 1846)	0.34395766738011424
  (1234, 488)	0.34395766738011424
  (1234, 1253)	0.5388818133206023
  (1234, 14

In [16]:
# getting the similarity scores through cosine similarity

similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [17]:
# without user input also not printing same song in recommendation
song_name = 'Numb'

list_of_all_titles = df['Track'].tolist()

find_close_match = difflib.get_close_matches(song_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_song = df[df.Track == close_match]['Index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_song]))


sorted_similar_songs = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Songs suggested for you : \n')

i = 1

for song in sorted_similar_songs:
  index = song[0]
  title_from_index = df[df.index==index]['Track'].values[0]
  if (i<26):
    if(title_from_index != song_name):
        print(i, '.',title_from_index)
        i+=1

Songs suggested for you : 

1 . Breaking the Habit
2 . Battle Symphony
3 . ROADS UNTRAVELED
4 . CASTLE OF GLASS
5 . LOST IN THE ECHO
6 . Talking to Myself
7 . Papercut
8 . One Step Closer
9 . Heavy (feat. Kiiara)
10 . Darkside
11 . Rise
12 . FRIENDS - R3hab Remix
13 . The Middle
14 . In My Mind
15 . REMEDY
16 . Sick Boy
17 . We Don't Care
18 . Ignite
19 . WTF (feat. Amber Van Day)
20 . Favela
21 . All For Love
22 . Forever Young
23 . High On Life (feat. Bonn)
24 . Sick Boy - Trobi Remix
25 . Lullaby


# Running code with additional information 

In [18]:
# with user input and artist name along with song name
song_name = input('song you already heard: ') # getting the song name from the user

list_of_all_titles = df['Track'].tolist() # creating a list with all the song names given in the dataset

find_close_match = difflib.get_close_matches(song_name, list_of_all_titles) # finding the close match for the song name given by the user

close_match = find_close_match[0]

index_of_the_song = df[df.Track == close_match]['Index'].values[0] # finding the index of the song

similarity_score = list(enumerate(similarity[index_of_the_song])) # getting a list of similar songs


sorted_similar_songs = sorted(similarity_score, key = lambda x:x[1], reverse = True) # sorting the songs based on their similarity score
# print the name of similar songs based on the index
print('Songs suggested for you : \n')

i = 1

for song in sorted_similar_songs:
  index = song[0]
  title_from_index = df[df.index==index]['Track'].values[0] + " - " +df[df.index==index]['Artist'].values[0] # will work even if artist name is removed 
  if (i<26):
    print(i, '.',title_from_index)
    i+=1

song you already heard: Faded
Songs suggested for you : 

1 . Faded - Alan Walker
2 . Alone - Alan Walker
3 . Faded - Alan Walker
4 . Sing Me to Sleep - Alan Walker
5 . Lost Control - Alan Walker, Sorana
6 . Diamond Heart - Alan Walker, Sophia Somajo
7 . I Don't Wanna Go - Alan Walker, Julie Bergan
8 . Lily - Alan Walker, K-391, Emelie Hollow
9 . On My Way - Alan Walker, Sabrina Carpenter, Farruko
10 . Darkside - Alan Walker, Au/Ra, Tomine Harket
11 . Time - Alan Walker Remix - Alan Walker, Hans Zimmer
12 . Spectre - Alan Walker
13 . Fade - Alan Walker
14 . The Spectre - Alan Walker
15 . The Drum - Alan Walker
16 . All Falls Down (feat. Juliander) - Alan Walker, Noah Cyrus, Digital Farm Animals, Juliander
17 . In Your Arms (with X Ambassadors) [Alan Walker Remix] - ILLENIUM, X Ambassadors, Alan Walker
18 . Sorry - Alan Walker, ISÁK
19 . Move Your Body - Alan Walker Remix - Sia, Alan Walker
20 . Sing Me to Sleep - Alan Walker
21 . Sweet Dreams - Alan Walker, Imanbek
22 . Sing Me to Slee

# Same code fo different song

In [20]:
#with user input and artist name along with song name
song_name = input('song you already heard: ') # getting the song name from the user

list_of_all_titles = df['Track'].tolist() # creating a list with all the song names given in the dataset

find_close_match = difflib.get_close_matches(song_name, list_of_all_titles) # finding the close match for the song name given by the user

close_match = find_close_match[0]

index_of_the_song = df[df.Track == close_match]['Index'].values[0] # finding the index of the song

similarity_score = list(enumerate(similarity[index_of_the_song])) # getting a list of similar songs


sorted_similar_songs = sorted(similarity_score, key = lambda x:x[1], reverse = True) # sorting the songs based on their similarity score
# print the name of similaHr songs based on the index
print('Songs suggested for you : \n')

i = 1

for song in sorted_similar_songs:
  index = song[0]
  title_from_index = df[df.index==index]['Track'].values[0] + " - " +df[df.index==index]['Artist'].values[0] # will work even  if artist name is removed 
  if (i<26):
    print(i, '.',title_from_index)
    i+=1

song you already heard: Arcade
Songs suggested for you : 

1 . Cradles - Sub Urban
2 . Cradles - Sub Urban
3 . Darkside - Alan Walker, Au/Ra, Tomine Harket
4 . Rise - Jonas Blue, Jack & Jack
5 . FRIENDS - R3hab Remix - Marshmello, Anne-Marie, R3HAB
6 . The Middle - Zedd, Maren Morris, Grey
7 . In My Mind - Dynoro, Gigi D'Agostino
8 . REMEDY - Alesso
9 . Sick Boy - The Chainsmokers
10 . We Don't Care - Sigala, The Vamps
11 . Ignite - Alan Walker, Julie Bergan, K-391, SEUNGRI
12 . WTF (feat. Amber Van Day) - HUGEL, Amber Van Day
13 . Favela - Ina Wroldsen, Alok
14 . All For Love - Tungevaag, Raaban, Richard Smitt
15 . Forever Young - John De Sohn, LIAMOO
16 . High On Life (feat. Bonn) - Martin Garrix, Bonn
17 . Sick Boy - Trobi Remix - The Chainsmokers, Trobi
18 . Lullaby - R3HAB, Mike Williams
19 . Polaroid - Jonas Blue, Liam Payne, Lennon Stella
20 . Right Now - Nick Jonas, Robin Schulz
21 . Solo (feat. Demi Lovato) - Wideboys Remix - Clean Bandit, Demi Lovato, Wideboys
22 . Whenever (

# Running the same code step by step

In [21]:
song_name = input(' Enter song name : ')

 Enter song name : Happier


In [22]:
list_of_all_titles = df['Track'].tolist()
print(list_of_all_titles)

['Darkside', 'Rise', 'FRIENDS - R3hab Remix', 'The Middle', 'In My Mind', 'REMEDY', 'Sick Boy', "We Don't Care", 'Ignite', 'WTF (feat. Amber Van Day)', 'Favela', 'All For Love', 'Forever Young', 'High On Life (feat. Bonn)', 'Sick Boy - Trobi Remix', 'Lullaby', 'Polaroid', 'Right Now', 'Solo (feat. Demi Lovato) - Wideboys Remix', 'Whenever (feat. Conor Maynard)', 'Like I Do', 'Blah Blah Blah', 'Ocean', 'Burn Out (feat. Dewain Whitmore)', 'Mama (feat. Ellie Goulding) - Tiësto’s Big Room Remix', 'Sing Me to Sleep', 'Hot2Touch', 'Glad You Came', 'Jackie Chan', 'Tie Me Down (with Elley Duhé)', 'Diamond Heart', 'Only You (with Little Mix)', 'One Kiss (with Dua Lipa)', 'Happy Now', 'Everybody Hates Me', 'Ring Ring (feat. Mabel & Rich The Kid)', 'Where Have You Gone (Anywhere)', 'Your Love', 'Fly', 'Be Your Friend\u202c\u202c', 'Magenta Riddim', 'BOOM', 'Azukita (Steve Aoki, Daddy Yankee, Play-N-Skillz & Elvis Crespo) (feat. Elvis Crespo)', 'Born To Be Yours', 'Speechless (feat. Erika Sirola)'

In [23]:
find_close_match = difflib.get_close_matches(song_name, list_of_all_titles)
print(find_close_match)

['Happier']


In [24]:
close_match = find_close_match[0]
print(close_match)

Happier


In [25]:


index_of_the_song = df[df.Track == close_match]['Index'].values[0]
print(index_of_the_song)

162


In [26]:


similarity_score = list(enumerate(similarity[index_of_the_song]))
print(similarity_score)

[(0, 0.0), (1, 0.0), (2, 0.15532765081620284), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.0), (38, 0.2531439646902891), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.0), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.0), (50, 0.0), (51, 0.0), (52, 0.0), (53, 0.0), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.0), (58, 0.0), (59, 0.0), (60, 0.0), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.0), (65, 0.0), (66, 0.0), (67, 0.0), (68, 0.0), (69, 0.0), (70, 0.0), (71, 0.0), (72, 0.0), (73, 0.0), (74, 0.0), (75, 0.0), (76, 0.0), (77, 0.0), (78, 0.0), (79, 0.0), (80, 0.0), (81, 0.0), (82, 0.0), (83, 0.0), (84, 0.0), (85, 0.0), (86, 0.0), (87, 0.0), (88, 0.0),

In [27]:


sorted_similar_songs = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_songs)

[(162, 1.0), (244, 0.48577590413167643), (775, 0.32656105856266054), (681, 0.3193676150626239), (982, 0.3158496564672184), (334, 0.2965603116035774), (930, 0.2921882953085301), (38, 0.2531439646902891), (877, 0.2517941914343977), (740, 0.23397011793962433), (161, 0.2161163340671786), (1091, 0.21288136020286222), (148, 0.21039731585938537), (249, 0.20336275462468326), (2, 0.15532765081620284), (400, 0.13381342581900768), (0, 0.0), (1, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.0), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.0), (50, 0.0), (51, 0.0), (52, 0.0), (53, 0.0), (54, 0.0), (5

In [28]:


print('Songs suggested for you : \n')

i = 1

for movie in sorted_similar_songs:
  index = movie[0]
  title_from_index = df[df.index==index]['Track'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Songs suggested for you : 

1 . Happier
2 . Pompeii
3 . Down
4 . Alone
5 . Mask Off - Marshmello Remix
6 . Happier Than Ever
7 . Before U
8 . Fly
9 . Moving On
10 . Silence
11 . FRIENDS
12 . Come & Go (with Marshmello)
13 . Wolves
14 . Here With Me
15 . FRIENDS - R3hab Remix
16 . Leave Before You Love Me (with Jonas Brothers)
17 . Darkside
18 . Rise
19 . The Middle
20 . In My Mind
21 . REMEDY
22 . Sick Boy
23 . We Don't Care
24 . Ignite
25 . WTF (feat. Amber Van Day)
26 . Favela
27 . All For Love
28 . Forever Young
29 . High On Life (feat. Bonn)
